name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Locaweb
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "."               # raiz do projeto
          remoteDir: "public_html"   # ou "web" se for Windows
